---
- hosts: bvtest 
  remote_user: ec2-user 
  become: yes
  become_method: sudo
  tasks:
  - name: Check EPEL repo
    stat: path="/etc/yum.repos.d/epel.repo"
    register: epel_repofile_result
  - name: Install EPEL repo.
    yum:
      name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
      state: present
    register: result
    when: not epel_repofile_result.stat.exists
  - name: Import EPEL GPG key.
    rpm_key:
      key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7"
      state: present
    when: not epel_repofile_result.stat.exists
  - name: install the latest rsyslogd
    yum:
      name: rsyslog
      state: latest
    notify: restart rsyslogd
  handlers:
  - name: restart rsyslogd
    service:
      name: rsyslog
      state: restarted 